la-mia-pizzeria-static/Models/Pizza.cs
using System.ComponentModel.DataAnnotations;
using la_mia_pizzeria_static.Validations;

namespace la_mia_pizzeria_static.Models
{
    public class Pizza
    {
        public int PizzaId { get; set; }

        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [StringLength(50, ErrorMessage = "Il nome non può avere più di 50 caratteri")]
        public string Name { get; set; }
      
        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [ImgValidation]
        public string ImgPath { get; set; }

        [Required(ErrorMessage = "Il campo è obbligatorio")]
        [Range(0, int.MaxValue, ErrorMessage = "Il prezzo dev'essere positivo")]
        public decimal Price { get; set; }

        public List<Ingredient>? Ingredients { get; set; }

        public int? CategoryId { get; set; }

        public Category? Category { get; set; }

        public static void Seed()
        {
            using (PizzaContext db = new PizzaContext())
            {

                var pizza = new Pizza()
                {
                    Name = "Marinara",
                    ImgPath = "~/img/marinara.jpg",
                    Price = 4.00m,
                    CategoryId = 1,
                    Ingredients = new List<Ingredient>
                    {
                        new Ingredient()
                        {
                            Name = "Pomodoro"
                        },
                        new Ingredient()
                        {
                            Name = "Origano"
                        }
                    }
                };

                db.Add(pizza);
                db.SaveChanges();

                pizza = new Pizza()
                {
                    Name = "Margherita",
                    ImgPath = "~/img/margherita.jpg",
                    Price = 4.00m,
                    CategoryId = 1,
                    Ingredients = new List<Ingredient>
                    {
                        db.Ingredients.Where(c => c.Name == "Pomodoro").FirstOrDefault(),
                        new Ingredient()
                        {
                            Name = "Mozzarella"
                        }
                    }
                };

                db.Add(pizza);
                db.SaveChanges();

                pizza = new Pizza()
                {
                    Name = "Capricciosa",
                    ImgPath = "~/img/capricciosa.jpg",
                    Price = 4.00m,
                    CategoryId = 1,
                    Ingredients = new List<Ingredient>
                    {
                        db.Ingredients.Where(c => c.Name == "Pomodoro").FirstOrDefault(),
                        db.Ingredients.Where(c => c.Name == "Mozzarella").FirstOrDefault(),
                        new Ingredient()
                        {
                            Name = "Prosciutto Cotto"
                        },
                        new Ingredient()
                        {
                            Name = "Funghi"
                        },
                        new Ingredient()
                        {
                            Name = "Olive"
                        }
                    }
                };

                db.Add(pizza);
                db.SaveChanges();

            }
        }
    }
}

la-mia-pizzeria-static/Controllers/Api/PizzasController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace la_mia_pizzeria_static.Controllers.Api
{
    [Route("api/[controller]/[action]")]
    [ApiController]
    public class PizzasController : ControllerBase
    {
        private IWebHostEnvironment Environment;
        private PizzaContext DB;

        public PizzasController(IWebHostEnvironment _environment, PizzaContext db)
        {
            Environment = _environment;
            DB = db;
        }

        [HttpGet]
        public IActionResult GetPizzas([FromQuery] string? name)
        {
            List<Pizza> pizze;

            if (name == null || name == "")
                pizze = DB.Pizzas.ToList();
            else
                pizze = DB.Pizzas.Where(p => p.Name.ToLower().Contains(name)).ToList();

            return Ok(pizze);
        }

        [HttpGet("{id}")]
        public IActionResult GetPizza(int id)
        {
            var pizza = DB.Pizzas.FirstOrDefault(p => p.PizzaId == id);

            if (pizza is null)
            {
                return NotFound();
            }

            return Ok(pizza);
        }

        [HttpPost]
        public IActionResult CreatePizza(Pizza pizza)
        {
            DB.Pizzas.Add(pizza);
            DB.SaveChanges();

            return Ok("Pizza creata correttamente!");
        }

        [HttpPut("{id}")]
        public IActionResult PutPizza(int id, [FromBody] Pizza pizza)
        {
            var savedPizza = DB.Pizzas.FirstOrDefault(p => p.PizzaId == id);

            if (savedPizza is null)
            {
                return NotFound();
            }

            savedPizza.Name = pizza.Name;
            savedPizza.Price = pizza.Price;
            savedPizza.ImgPath = pizza.ImgPath;
            savedPizza.CategoryId = pizza.CategoryId;

            DB.SaveChanges();

            return Ok("Pizza modificata correttamente!");
        }

        [HttpDelete("{id}")]
        public IActionResult DeletePizza(int id)
        {
            var savedPizza = DB.Pizzas.FirstOrDefault(p => p.PizzaId == id);

            if (savedPizza is null)
            {
                return NotFound();
            }

            DB.Pizzas.Remove(savedPizza);
            DB.SaveChanges();

            return Ok("Pizza eliminata correttamente!");
        }
    }
}

la-mia-pizzeria-static/Controllers/PizzaController.cs
using la_mia_pizzeria_static.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Hosting;
using System.Globalization;
using System.Web;

namespace la_mia_pizzeria_static.Controllers
{
    [Authorize]
    public class PizzaController : Controller
    {
        private IWebHostEnvironment Environment;
        private PizzaContext DB;

        public PizzaController(IWebHostEnvironment _environment, PizzaContext db)
        {
            Environment = _environment;
            DB = db;
        }
        public IActionResult Index()
        {
            List<Pizza> pizze = DB.Pizzas.ToList<Pizza>();

            return View(pizze);
        }

        public IActionResult Details(int Id)
        {
            Pizza pizza;
            try
            {
                pizza = DB.Pizzas.Include(p => p.Ingredients).First(p => p.PizzaId == Id);

                return View(pizza);  

            }catch (Exception)
            { 
                return View("NotFound", Id);    
            }
            
        }

        [Authorize(Roles = "ADMIN")]
        public IActionResult Create()
        {
            List<Category> categories = DB.Categories.ToList();

            PizzaFormModel model = new PizzaFormModel();
            model.Pizza = new Pizza();
            model.Categories = categories;

            List<Ingredient> ingredients = DB.Ingredients.ToList();
            List<SelectListItem> listIngredients = new List<SelectListItem>();

            foreach (Ingredient ingredient in ingredients)
            {
                listIngredients.Add(
                        new SelectListItem()
                        {
                            Text = ingredient.Name,
                            Value = ingredient.Id.ToString()
                        }
                );
            }

            model.Ingredients = listIngredients;

            return View(model);
        }

        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(PizzaFormModel data, IFormFile img)
        {
            data.Pizza.ImgPath = Path.Combine(Environment.WebRootPath, "img", img.FileName);

            ModelState.ClearValidationState("Pizza.ImgPath");

            TryValidateModel(data);

            if (!ModelState.IsValid)
            {
                List<Category> category = DB.Categories.ToList();
                data.Categories = category;

                List<Ingredient> ingredients = DB.Ingredients.ToList();
                List<SelectListItem> listIngredients = new List<SelectListItem>();

                foreach (Ingredient ingredient in ingredients)
                {
                    listIngredients.Add
                    (
                        new SelectListItem()
                        {
                            Text = ingredient.Name,
                            Value = ingredient.Id.ToString()
                        }
                    );
                }
                data.Ingredients = listIngredients;
                return View("Create", data);
            }

            using (var stream = System.IO.File.Create(data.Pizza.ImgPath))
            {
                await img.CopyToAsync(stream);
            }

            Pizza pizzaToCreate = new Pizza();
            pizzaToCreate.Name = data.Pizza.Name;
            pizzaToCreate.Ingredients = new List<Ingredient>();
            pizzaToCreate.ImgPath = "~/" + Path.GetRelativePath(Environment.WebRootPath, data.Pizza.ImgPath);
            pizzaToCreate.Price = data.Pizza.Price;
            pizzaToCreate.CategoryId = data.Pizza.CategoryId;

            if(data.SelectedIngredients != null)
            {
                foreach (string selectedIngredientId in data.SelectedIngredients)
                {
                    int selectIntIngredientId = int.Parse(selectedIngredientId);
                    Ingredient ingredient = DB.Ingredients.FirstOrDefault(m => m.Id == selectIntIngredientId);
                    pizzaToCreate.Ingredients.Add(ingredient);
                }
            }


            DB.Pizzas.Add(pizzaToCreate);
            DB.SaveChanges();

            return RedirectToAction("Index");
        }

        [Authorize(Roles = "ADMIN")]
        [HttpGet]
        public IActionResult Edit(int Id)
        {
            Pizza? pizza = DB.Pizzas.Include(p => p.Ingredients).FirstOrDefault(p => p.PizzaId == Id);

            if (pizza == null)
                return View("NotFound", Id);
            else
            {
                List<Category> categories = DB.Categories.ToList();

                PizzaFormModel model = new PizzaFormModel();
                model.Pizza = pizza;
                model.Categories = categories;

                List<Ingredient> ingredients = DB.Ingredients.ToList();
                List<SelectListItem> listIngredients = new List<SelectListItem>();
                foreach (Ingredient ingredient in ingredients)
                {
                    listIngredients.Add(
                        new SelectListItem()
                        {
                            Text = ingredient.Name,
                            Value = ingredient.Id.ToString(),
                            Selected = pizza.Ingredients.Any(m => m.Id == ingredient.Id)
                        }
                    );
                }
                model.Ingredients = listIngredients;
                return View(model);
            }
            
        }

        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(PizzaFormModel data, IFormFile img)
        {
            if (img != null)
            {
                var imgToDelete = Path.GetFullPath(Path.Combine(Environment.WebRootPath, data.Pizza.ImgPath.Substring(2)));
                System.IO.File.Delete(imgToDelete);

                data.Pizza.ImgPath = Path.Combine(Environment.WebRootPath, "img", img.FileName);

                ModelState.ClearValidationState("Pizza.ImgPath");

                TryValidateModel(data);
            } else
            {
                ModelState["img"].ValidationState = ModelValidationState.Valid;
            }

            if (!ModelState.IsValid)
            {
                data.Categories = DB.Categories.ToList();

                List<Ingredient> ingredients = DB.Ingredients.ToList();
                List<SelectListItem> listIngredients = new List<SelectListItem>();
                foreach (Ingredient ingredient in ingredients)
                {
                    listIngredients.Add(
                        new SelectListItem()
                        {
                            Text = ingredient.Name,
                            Value = ingredient.Id.ToString(),
                        }
                    );
                }

                data.Ingredients = listIngredients;
                return View("Edit", data);
            }

            if (img != null)
            {
                using (var stream = System.IO.File.Create(data.Pizza.ImgPath))
                {
                    await img.CopyToAsync(stream);
                }
            }

            Pizza pizzaToEdit = DB.Pizzas.Include(p => p.Ingredients).FirstOrDefault(p => p.PizzaId == data.Pizza.PizzaId);
            pizzaToEdit.Ingredients.Clear();

            pizzaToEdit.Name = data.Pizza.Name;
            pizzaToEdit.ImgPath = img == null ? data.Pizza.ImgPath : "~/" + Path.GetRelativePath(Environment.WebRootPath, data.Pizza.ImgPath);
            pizzaToEdit.Price = data.Pizza.Price;
            pizzaToEdit.CategoryId = data.Pizza.CategoryId;

            if (data.SelectedIngredients != null)
            {
                foreach (string selectedIngredientId in data.SelectedIngredients)
                {
                    int selectIntIngredientId = int.Parse(selectedIngredientId);
                    Ingredient ingredient = DB.Ingredients
                    .Where(m => m.Id == selectIntIngredientId)
                    .FirstOrDefault();
                    pizzaToEdit.Ingredients.Add(ingredient);
                }
            }

            DB.SaveChanges();

            return RedirectToAction("Index");
            
        }

        [Authorize(Roles = "ADMIN")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id)
        {
     
            Pizza? pizzaToDelete = DB.Pizzas.Where(pizza => pizza.PizzaId == id).FirstOrDefault();

            if (pizzaToDelete != null)
            {
                var imgToDelete = Path.GetFullPath(Path.Combine(Environment.WebRootPath, pizzaToDelete.ImgPath.Substring(2)));
                System.IO.File.Delete(imgToDelete);

                DB.Pizzas.Remove(pizzaToDelete);

                DB.SaveChanges();

                return RedirectToAction("Index");
            }
            else
            {
                return NotFound();
            }
            
        }
    }
}

la-mia-pizzeria-static/Views/Pizza/Create.cshtml
@model PizzaFormModel

@{
    Layout = "_Layout";
    ViewData["Title"] = $"Aggiungi Pizza";
}

<div class="container">
    <form asp-controller="Pizza" asp-action="Create" enctype="multipart/form-data" method="post">
        @Html.AntiForgeryToken()
        <div class="mb-3">
            <strong>Nome:</strong>
            <input asp-for="Pizza.Name" class="d-block w-100" />
            <span asp-validation-for="Pizza.Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <strong>Immagine:</strong>
            <input type="file" name="img" class="d-block w-100" />
            <span asp-validation-for="Pizza.ImgPath" type="file" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <strong>Prezzo:</strong>
            <input asp-for="Pizza.Price" class="d-block w-100" />
            <span asp-validation-for="Pizza.Price" class="text-danger"></span>
        </div>

        <div>
            <strong>Category:</strong>
            <select asp-for="Pizza.CategoryId" rows="10" class="d-block w-100">
                <option value=""></option>
                @foreach (Category category in Model.Categories)
                {
                    @if (Model.Pizza.CategoryId == category.Id)
                    {
                        <option value="@category.Id" selected>@category.Nome</option>
                    }
                    else
                    {
                        <option value="@category.Id">@category.Nome</option>
                    }
                }
            </select>
        </div>

        <div class="mb-3">
            <strong>Ingredients:</strong>
            <select asp-for="SelectedIngredients"
                    multiple="multiple"
                    size="10"
                    class="form-control mb-2 mr-sm-2 ml-sm-3 leftList"
                    asp-items="@Model.Ingredients">
            </select>
        </div>

        <div class="text-end">
            <input type="submit" class="btn btn-small btn-info" value="Salva">
        </div>
    </form>
</div>
 

la-mia-pizzeria-static/Views/Pizza/Details.cshtml
@model Pizza;
@{
    Layout = "_Layout";
    ViewData["Title"] = $"Pizza {Model.Name}";
}

<div class="container">
    <div class="col-12">
        <div class="d-flex align-items-center">
            <h1>Dettaglio pizza:</h1>
        </div>

        <div>
            <img src="@Url.Content(Model.ImgPath)" />
        </div>

        <p>
            <strong>Nome:</strong> @Model.Name
        </p>

        <p>
            <strong>Ingredienti:</strong> 
            @{var last = Model.Ingredients.Last();}
            @foreach(Ingredient ingredient in Model.Ingredients) 
            { 
                if(ingredient.Equals(last))
                    @ingredient.Name
                else
                    @(ingredient.Name + ", ") 
            }
        </p>

        <p>
            <strong>Prezzo:</strong> € @Model.Price.ToString()
        </p>
    </div>
</div>

la-mia-pizzeria-static/Views/Pizza/Edit.cshtml
@model PizzaFormModel

@{
    Layout = "_Layout";
    ViewData["Title"] = "Modifica Pizza";
}

<div class="container">
    <form asp-controller="Pizza" asp-action="Edit" enctype="multipart/form-data" method="post">
        @Html.AntiForgeryToken()
        @Html.Hidden("Pizza.PizzaId", Model.Pizza.PizzaId)
        @Html.Hidden("Pizza.ImgPath", Model.Pizza.ImgPath)
        <div class="mb-3">
            <strong>Nome:</strong>
            <input asp-for="Pizza.Name" class="d-block w-100" />
            <span asp-validation-for="Pizza.Name" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <strong>Immagine:</strong>
            <input type="file" name="img" class="d-block w-100" />
            <span asp-validation-for="Pizza.ImgPath" type="file" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <strong>Prezzo:</strong>
            <input asp-for="Pizza.Price" class="d-block w-100" />
            <span asp-validation-for="Pizza.Price" class="text-danger"></span>
        </div>

        <div>
            <strong>Category:</strong>
            <select asp-for="Pizza.CategoryId" rows="10" class="d-block w-100">
                <option value=""></option>
                @foreach (Category category in Model.Categories)
                {
                    @if (Model.Pizza.CategoryId == category.Id)
                    {
                        <option value="@category.Id" selected>@category.Nome</option>
                    }
                    else
                    {
                        <option value="@category.Id">@category.Nome</option>
                    }
                }
            </select>
        </div>

        <div class="mb-3">
            <strong>Ingredients:</strong>
            <select asp-for="SelectedIngredients"
                    multiple="multiple"
                    size="10"
                    class="form-control mb-2 mr-sm-2 ml-sm-3 leftList"
                    asp-items="@Model.Ingredients">
            </select>
        </div>

        <div class="text-end">
            <input type="submit" class="btn btn-small btn-info" value="Salva">
        </div>
    </form>
</div>
 

la-mia-pizzeria-static/Views/Pizza/Index.cshtml
@{
    Layout = "_Layout";
    ViewData["Title"] = "Pizzeria da Luigi";
}
@model List<Pizza>;

<div class="container">
    <div class="row mt-3">
        <div class="col-5"></div>
        @if (User.IsInRole("ADMIN"))
        {
            <a class="btn btn-primary col-2 justify-content-center" href="@Url.Action("Create", "Pizza")">Aggiungi Pizza</a>
        }
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Nome</th>
                    <th scope="col">Foto</th>
                    <th scope="col">Prezzo</th>
                    <th scope="col">Links</th>
                </tr>
            </thead>
            <tbody>
                @foreach(Pizza pizza in Model)
                {
                <tr>
                    <th scope="row">@pizza.Name</th>
                    <td>
                        <img src="@Url.Content(@pizza.ImgPath)" alt="Pizza @pizza.Name" class="img-fluid" style="height:200px">
                    </td>
                    <td>€ @(pizza.Price.ToString())</td>
                    <td>
                        <a href="@Url.Action("Details", "Pizza", new {Id=@pizza.PizzaId})">Details</a>
                        @if (User.IsInRole("ADMIN"))
                        {   
                            <a class="btn btn-primary" href="@Url.Action("Edit", "Pizza", new {Id=@pizza.PizzaId})"><i class="fa-solid fa-pen-to-square"></i></a>
                            <form asp-controller="Pizza" asp-action="Delete" asp-route-id="@pizza.PizzaId" method="post">
                                @Html.AntiForgeryToken()
                                <button type="submit" class="btn btn-danger" onclick="return confirm('sei sicuro?')">
                                    <i class="fa-solid fa-trash"></i>
                                </button>
                            </form>
                        }
                    </td>
                </tr>
                    
                }
            </tbody>
        </table>
    </div>
</div>

la-mia-pizzeria-static/Views/Pizza/NotFound.cshtml
@model int

<h1>La Pizza numero @Model non è stato trovato</h1>